import './globals.css'
import {MainProvider} from "@/app/components/MainContext"
import Header from '@/app/components/Header'
import Footer from '@/app/components/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MainProvider>
      <body>
      <Header />
      {children}
      <Footer />
      </body>
      </MainProvider>
    </html>
  )
}
