import '@/app/globals.css'
import {MainProvider} from "@/app/components/MainContext"
import Header from '@/app/components/Header'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function LoginLayout({ children }) {
  return (
    <div>
      {children}
    </div>
  )
}
